from app.schemas.asset_placement import (
    AssetAdjustment,
    AssetAdjustmentRequest,
    AssetPlacementCreate,
    AssetPlacementListResponse,
    AssetPlacementResponse,
    AssetPlacementUpdate,
    PlacedAssetInfo,
    PlacementStatistics,
)
from app.schemas.auth import (
    GoogleOAuthRequest,
    GoogleUserInfo,
    Token,
    TokenPayload,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
)
from app.schemas.exclusion_zone import (
    BufferApplyRequest,
    ExclusionZoneCreate,
    ExclusionZoneImportRequest,
    ExclusionZoneImportResponse,
    ExclusionZoneListResponse,
    ExclusionZoneResponse,
    ExclusionZoneUpdate,
    SpatialQueryRequest,
    SpatialQueryResponse,
)
from app.schemas.export import (
    AvailableFormatsResponse,
    BulkExportRequest,
    BulkExportResponse,
    CSVExportRequest,
    DXFExportRequest,
    ExportFormat,
    ExportHistoryItem,
    ExportHistoryResponse,
    ExportLayer,
    ExportMetadata,
    ExportRequest,
    ExportResponse,
    GeoJSONExportRequest,
    KMZExportRequest,
    PDFReportRequest,
    ShapefileExportRequest,
)
from app.schemas.file import (
    FileAssignRequest,
    FileUploadResponse,
    FileValidationResponse,
    UploadedFileListResponse,
    UploadedFileResponse,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectListResponse,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.road_network import (
    IntersectionInfo,
    RoadNetworkAdjustmentRequest,
    RoadNetworkCreate,
    RoadNetworkListResponse,
    RoadNetworkResponse,
    RoadNetworkStatistics,
    RoadNetworkUpdate,
    RoadSegmentAdjustment,
    RoadSegmentInfo,
)
from app.schemas.terrain import (
    AspectStatsResponse,
    ElevationAtPointsRequest,
    ElevationAtPointsResponse,
    ElevationStatsResponse,
    SlopeStatsResponse,
    TerrainAnalysisCreate,
    TerrainAnalysisListResponse,
    TerrainAnalysisResponse,
    TerrainProfileRequest,
    TerrainProfileResponse,
)

__all__ = [
    # Auth schemas
    "Token",
    "TokenPayload",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "GoogleOAuthRequest",
    "GoogleUserInfo",
    # Project schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    # File schemas
    "FileUploadResponse",
    "FileValidationResponse",
    "UploadedFileResponse",
    "UploadedFileListResponse",
    "FileAssignRequest",
    # Terrain schemas
    "TerrainAnalysisCreate",
    "TerrainAnalysisResponse",
    "TerrainAnalysisListResponse",
    "ElevationStatsResponse",
    "SlopeStatsResponse",
    "AspectStatsResponse",
    "TerrainProfileRequest",
    "TerrainProfileResponse",
    "ElevationAtPointsRequest",
    "ElevationAtPointsResponse",
    # Exclusion zone schemas
    "ExclusionZoneCreate",
    "ExclusionZoneUpdate",
    "ExclusionZoneResponse",
    "ExclusionZoneListResponse",
    "ExclusionZoneImportRequest",
    "ExclusionZoneImportResponse",
    "BufferApplyRequest",
    "SpatialQueryRequest",
    "SpatialQueryResponse",
    # Asset placement schemas
    "AssetPlacementCreate",
    "AssetPlacementUpdate",
    "AssetPlacementResponse",
    "AssetPlacementListResponse",
    "PlacedAssetInfo",
    "PlacementStatistics",
    "AssetAdjustment",
    "AssetAdjustmentRequest",
    # Road network schemas
    "RoadNetworkCreate",
    "RoadNetworkUpdate",
    "RoadNetworkResponse",
    "RoadNetworkListResponse",
    "RoadSegmentInfo",
    "IntersectionInfo",
    "RoadNetworkStatistics",
    "RoadSegmentAdjustment",
    "RoadNetworkAdjustmentRequest",
    # Export schemas
    "ExportFormat",
    "ExportLayer",
    "ExportRequest",
    "PDFReportRequest",
    "GeoJSONExportRequest",
    "KMZExportRequest",
    "ShapefileExportRequest",
    "CSVExportRequest",
    "DXFExportRequest",
    "ExportMetadata",
    "ExportResponse",
    "ExportHistoryItem",
    "ExportHistoryResponse",
    "AvailableFormatsResponse",
    "BulkExportRequest",
    "BulkExportResponse",
]
